kafka:
  bootstrap-servers: localhost:9092
  topic:
    oservice: wjma-topic-oservice
    
spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/maddoxbd
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5